[package]
name = "mongodb-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
futures = "0.3.26"
mongodb = "2.4.0"
serde = "1.0.152"
serde_json = "1.0.94"
